# Generated by Django 5.0.2 on 2024-07-23 11:53

import django.db.models.deletion
import django.utils.timezone
import system.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=system.models.uploaded_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('car_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('num_of_seats', models.IntegerField()),
                ('cost_par_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('content', models.TextField()),
                ('like', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateMsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=255)),
                ('dealer_name', models.CharField(max_length=255)),
                ('cell_no', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('date_from', models.DateField(default=django.utils.timezone.now)),
                ('date_to', models.DateField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
