# Generated by Django 4.2.11 on 2025-07-15 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("system", "0003_order_created_at_order_daily_rate_order_email_sent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient_email", models.EmailField(max_length=254)),
                ("sender_email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=255)),
                (
                    "email_type",
                    models.CharField(
                        choices=[
                            ("booking_confirmation", "Booking Confirmation"),
                            ("booking_status_update", "Booking Status Update"),
                            ("admin_notification", "Admin Notification"),
                            ("contact_form", "Contact Form"),
                            ("password_reset", "Password Reset"),
                            ("verification", "Email Verification"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent Successfully"),
                            ("failed", "Failed to Send"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("html_content", models.TextField(blank=True)),
                ("text_content", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.IntegerField(default=0)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="system.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Log",
                "verbose_name_plural": "Email Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient_email", "email_type"],
                        name="system_emai_recipie_c9c4bb_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="system_emai_status_40af11_idx",
                    ),
                ],
            },
        ),
    ]
