# Generated by Django 4.2.11 on 2025-07-16 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("system", "0005_chatbotresponse_chatroom_chatmessage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="assigned_agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_rooms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("closed", "Closed"),
                    ("escalated", "Escalated to Agent"),
                    ("bot_only", "Bot Only"),
                    ("pending_escalation", "Pending Escalation"),
                ],
                default="bot_only",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_rooms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
