# Generated by Django 4.2.11 on 2025-07-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0006_chatroom_assigned_agent_alter_chatroom_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="drop_off_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="drop_off_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="pick_up_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="pick_up_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
