# Generated by Django 4.2.11 on 2025-07-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="privatemsg",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Private Message",
                "verbose_name_plural": "Private Messages",
            },
        ),
        migrations.AddField(
            model_name="privatemsg",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="privatemsg",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="privatemsg",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
