# Generated by Django 4.2.11 on 2025-07-22 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("system", "0007_order_drop_off_date_order_drop_off_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="privatemsg",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="privatemsg",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="privatemsg",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("normal", "Normal"),
                    ("high", "High"),
                    ("urgent", "Urgent"),
                ],
                default="normal",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="privatemsg",
            name="responded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="message_responses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="privatemsg",
            name="response_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="privatemsg",
            name="response_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="privatemsg",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("read", "Read"),
                    ("replied", "Replied"),
                    ("closed", "Closed"),
                ],
                default="new",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="privatemsg",
            name="subject",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="privatemsg",
            name="user_agent",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="privatemsg",
            index=models.Index(
                fields=["status", "priority"], name="system_priv_status_5c3c26_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="privatemsg",
            index=models.Index(
                fields=["email", "created_at"], name="system_priv_email_bd1af3_idx"
            ),
        ),
    ]
