# Generated by Django 4.2.23 on 2025-07-24 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_paymentmethod_paymenttransaction_paymentwebhook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('pay_later', 'Pay Later'), ('crypto', 'Cryptocurrency')], max_length=50, unique=True),
        ),
    ]
