# Generated by Django 4.2.11 on 2025-09-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0010_alter_paymentmethod_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentmethod",
            name="name",
            field=models.CharField(
                choices=[
                    ("paystack", "Paystack"),
                    ("stripe", "Stripe"),
                    ("paypal", "PayPal"),
                    ("bank_transfer", "Bank Transfer"),
                    ("cash", "Cash"),
                    ("pay_later", "Pay Later"),
                    ("crypto", "Cryptocurrency"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
